config/routes.rb
NppesData::Application.routes.draw do
  resources :providers do
    collection do
      get  :search
      post :results
    end
  end
  match "/npi/:npi" => 'providers#show'

  root :to => 'providers#search'
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  has_many :provider_identifiers
  has_many :provider_taxonomies

  scope :with_npi,              lambda {|param| param.blank? ? scoped : where("npi = ?", param) }

  scope :city,                  lambda {|param| param.blank? ? scoped : where("(provider_business_mailing_address_city_name = ? OR provider_business_practice_location_address_city_name = ?)", param, param) }
  scope :state,                 lambda {|param| param.blank? ? scoped : where("(provider_mailing_address_state_name = ? OR provider_business_practice_location_address_state_name = ?)", param, param) }
  scope :postal_code,           lambda {|param| param.blank? ? scoped : where("(provider_business_mailing_address_postal_code = ? OR provider_business_practice_location_address_postal_code = ?)", param, param) }

  scope :mailing_city,          lambda {|param| param.blank? ? scoped : where("provider_business_mailing_address_city_name = ?", param) }
  scope :mailing_state,         lambda {|param| param.blank? ? scoped : where("provider_mailing_address_state_name = ?", param) }
  scope :mailing_postal_code,   lambda {|param| param.blank? ? scoped : where("provider_business_mailing_address_postal_code = ?", param) }

  scope :practice_city,         lambda {|param| param.blank? ? scoped : where("provider_business_practice_location_address_city_name = ?", param) }
  scope :practice_state,        lambda {|param| param.blank? ? scoped : where("provider_business_practice_location_address_state_name = ?", param) }
  scope :practice_postal_code,  lambda {|param| param.blank? ? scoped : where("provider_business_practice_location_address_postal_code = ?", param) }

  scope :provider_telephone,    lambda {|param| param.blank? ? scoped : where("provider_business_mailing_address_telephone_number = ?", param) }
  scope :practice_telephone,    lambda {|param| param.blank? ? scoped : where("provider_business_practice_location_address_telephone_number = ?", param) }
  scope :official_telephone,    lambda {|param| param.blank? ? scoped : where("authorized_official_telephone_number = ?", param) }

  scope :phone,                 lambda {|param| param.blank? ? scoped : where("(provider_business_mailing_address_telephone_number = ? OR provider_business_practice_location_address_telephone_number = ? OR authorized_official_telephone_number = ?)", param, param, param) }

  def self.wildcard_search(field, value)
    if value.blank?
      scoped
    elsif value =~ /\*/
      where("#{field} LIKE ?", value.gsub("*", "%"))
    else
      where("#{field} = ?", value)
    end
  end

  def self.first_name(param)
    wildcard_search('provider_first_name', param)
  end

  def self.last_name(param)
    wildcard_search('provider_last_name', param)
  end

  def self.organization(param)
    wildcard_search('provider_organization_name', param)
  end

  def name
    if entity_type_code == '1'
      [provider_first_name, provider_middle_name, provider_last_name, provider_name_suffix_text, provider_credential_text].join(' ')
    else
      self.provider_organization_name
    end
  end

  def other_name
    ret = if entity_type_code == '1'
            [name_type_code_xref(provider_other_last_name_type_code), provider_other_first_name, provider_other_middle_name, provider_other_last_name, provider_other_name_suffix_text, provider_other_credential_text].join(' ')
          else
            name_type_code_xref(provider_other_organization_name_type_code) + ' ' + self.provider_other_organization_name
          end

    ret.to_s.strip.blank? ? nil : ret
  end

  def name_type_code_xref(code)
    case code
    when '1' then 'Former:'
    when '2' then 'Professional:'
    when '3' then 'D/B/A:'
    when '4' then 'Former:'
    when '5' then 'Other:'
    else ''
    end
  end
end

app/models/provider_identifier.rb
class ProviderIdentifier < ActiveRecord::Base
  belongs_to :provider

  def type
    case type_code
    when 'LC' then 'License'
    when '01' then 'Other'
    when '02' then 'Medicare Upin'
    when '04' then 'Medicare ID - Other'
    when '05' then 'Medicaid'
    when '06' then 'Medicare Oscar/Cert'
    when '07' then 'Medicare NSC'
    when '08' then 'Medicare PIN'
    end
  end
end

app/models/provider_taxonomy.rb
class ProviderTaxonomy < ActiveRecord::Base
  belongs_to :provider

  def taxonomy_details
    @taxonomy_details ||= Hippo::CodeLists::TaxonomyCodes[self.taxonomy]
  end

  def description
    taxonomy_details[:classification] + (taxonomy_details[:specialization].present? ? "/#{taxonomy_details[:specialization]}" : '')
  end

  def definition
    taxonomy_details[:definition]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def search;end

  def results
    redirect_to providers_path(params: params)
  end

  def show
    @provider = Provider.where('id = ? OR npi = ?',params[:id], params[:npi]).limit(1).first
  end

  def index
    if valid_search?
      @providers = Provider.first_name(params[:first_name]).
                            last_name(params[:last_name]).
                            organization(params[:organization]).
                            with_npi(params[:npi]).
                            city(params[:city]).
                            state(params[:state]).
                            postal_code(params[:postal_code]).
                            phone(sanitize_phone(params[:phone])).
                            limit(200)
    else
      flash[:alert] = 'You must search using at least one of the following indexed fields (NPI, Org Name, Phone, Last Name).'
    end
  end

  def sanitize_phone(p)
    p.nil? ? nil : p.gsub(/(\D+)/,'')
  end

  def valid_search?
    params.any? { |key, value| [:npi, :organization, :state, :phone, :last_name].include?(key.to_sym) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def twitterized_type(type)
    case type
      when :alert
        "warning"
      when :error
        "error"
      when :notice
        "info"
      when :success
        "success"
      else
        type.to_s
    end
  end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/layouts/_topnav.html.erb
<div class="navbar navbar-fixed-top no-print" id="topnav">
  <div class="navbar-inner">
    <div class="container">
      <a  class="brand" href="<%= root_path %>">NppesData</a>
      <ul class="nav">
        <li class="active"><a href="<%= root_path %>">Home</a></li>
        <li><a href="<%= search_providers_path %>">Search</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NPPES Data</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>
  <%= render 'layouts/topnav' %>
  <div class="flash-container">
      <% if flash[:notice] %>
        <div class="alert info flash-body"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert error flash-body"><%= flash[:alert] %></div>
      <% end %>
    <script type="text/javascript">setTimeout("$('.flash-container').fadeOut('fast')", 2500);</script>
  </div>

  <%= yield %>
  </body>
</html>

app/views/providers/index.html.erb
<% if @providers.to_a.length > 0 %>
  <h1>Listing providers</h1>
  <table class="table">
    <thead>
      <tr>
        <th>NPI</th>
        <th>Provider Name</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Postal Code</th>
        <th>Show</th>
      </tr>
    </thead>

  <% @providers.each do |provider| %>
    <tr>
      <td><%= provider.npi %></td>
      <td><%= provider.name %></td>
      <td><%= provider.provider_first_line_business_address %></td>
      <td><%= provider.provider_business_mailing_address_city_name %></td>
      <td><%= provider.provider_mailing_address_state_name %></td>
      <td><%= provider.provider_business_mailing_address_postal_code %></td>
      <td><%= link_to 'Show', provider %></td>
    </tr>
  <% end %>
  </table>
  <br/>
<% else %>
  <h1>No providers found using the criteria specified!!</h1>
<% end -%>

app/views/providers/search.html.erb
<div class="container" id='individual_search' style="display:false;">
  <h2>Search</h2>
  <%= form_tag(results_providers_path, :method => 'post' ) do %>
    <%= hidden_field_tag :search, :true %>
    <div class="row">
      <div class="span3">
        <%= label_tag :npi, 'NPI' %>
        <%= text_field_tag :npi, params[:npi], :class => 'search-field' %>
      </div>
    </div>
    <div class="row">
      <div class="span3">
        <%= label_tag :organization, 'Organization Name' %>
        <%= text_field_tag :organization, params[:organization], :class => 'search-field' %>
      </div>
      <div class="span3">
        <%= label_tag :last_name %>
        <%= text_field_tag :last_name, params[:last_name], :class => 'search-field' %>
      </div>
      <div class="span3">
        <%= label_tag :first_name %>
        <%= text_field_tag :first_name, params[:first_name], :class => 'search-field' %>
      </div>
    </div>
    <div class="row">
      <div class="span3">
        <%= label_tag :city %>
        <%= text_field_tag :city, params[:city], :class => 'search-field' %>
      </div>
      <div class="span3">
        <%= label_tag :state %>
        <%= text_field_tag :state, params[:state], :class => 'search-field' %>
      </div>
      <div class="span3">
        <%= label_tag :postal_code %>
        <%= text_field_tag :postal_code, params[:postal_code], :class => 'search-field' %>
      </div>
    </div>
    <div class="row">
      <div class="span3">
        <%= label_tag :phone %>
        <%= text_field_tag :phone, params[:phone], :class => 'search-field' %>
      </div>
    </div>
    <div>
      <%= submit_tag "Search", :class => 'btn primary', :name => nil %>
    </div>
  </div>
  <% end %>
</div>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<fieldset>
  <legend>Provider Information</legend>
  <p>
    <b>Name:</b>
    <%= @provider.name %>
  </p>
  <% if @provider.other_name %>
    <p>
      <b>Other Name:</b>
      <%= @provider.other_name %>
    </p>
  <% end %>
  <% if @provider.entity_type_code == '1' %>
    <p>
      <b>Gender:</b>
      <%= @provider.provider_gender_code %>
    </p>
  <% else %>
    <p>
      <b>Sole Proprieter?:</b>
      <%= @provider.is_sole_proprietor %>
    </p>
  <% end %>
</fieldset>
<fieldset>
  <legend>NPI Information</legend>
  <p>
    <b>NPI:</b>
    <%= @provider.npi %>
  </p>
  <p>
    <b>Entity Type:</b>
    <%= @provider.entity_type_code %>
  </p>
  <p>
    <b>Enumeration Date:</b>
    <%= @provider.provider_enumeration_date %>
  </p>
  <p>
    <b>Last Update Date:</b>
    <%= @provider.last_update_date %>
  </p>
  <p>
    <b>Replacement NPI:</b>
    <%= @provider.replacement_npi %>
  </p>
  <p>
    <b>Deactivation Date:</b>
    <%= @provider.npi_deactivation_date %>
  </p>
  <p>
    <b>Reactivation Date:</b>
    <%= @provider.npi_reactivation_date %>
  </p>
</fieldset>
<fieldset>
  <legend>Provider Business Practice Location Address</legend>
  <p>
    <b>Address:</b>
    <div><%= @provider.provider_first_line_business_practice_location_address %> <%= @provider.provider_second_line_business_practice_location_address %><br/>
    <%= @provider.provider_business_practice_location_address_city_name %>, <%= @provider.provider_business_practice_location_address_state_name %>  <%= @provider.provider_business_practice_location_address_postal_code %></div>
  </p>
  <p>
    <b>Phone Number:</b>
    <%= @provider.provider_business_practice_location_address_telephone_number %>
  </p>
  <p>
    <b>Fax Number:</b>
    <%= @provider.provider_business_practice_location_address_fax_number %>
  </p>
</fieldset>
<fieldset>
  <legend>Provider Business Mailing Address</legend>
  <p>
    <b>Address:</b>
    <div><%= @provider.provider_first_line_business_address %><br/>
    <%= @provider.provider_business_mailing_address_city_name %>, <%= @provider.provider_mailing_address_state_name %>  <%= @provider.provider_business_mailing_address_postal_code %></div>
  </p>
  <p>
    <b>Phone Number:</b>
    <%= @provider.provider_business_mailing_address_telephone_number %>
  </p>
  <p>
    <b>Fax Number:</b>
    <%= @provider.provider_business_mailing_address_fax_number %>
  </p>
</fieldset>
<fieldset>
  <legend>Taxonomies</legend>

  <table class="table">
    <thead>
      <th>Primary</th>
      <th>Taxonomy</th>
      <th>Description</th>
    </thead>
    <tbody>
      <% @provider.provider_taxonomies.each do |tax| %>
        <tr>
          <td class="span1"><%= tax.primary %></td>
          <td class="span1"><%= tax.taxonomy %></td>
          <td class="span10"><b><%= tax.description %></b> - <%= tax.definition %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</fieldset>
<fieldset>
  <legend>Provider Numbers</legend>

  <table class="table">
    <thead>
      <th>Type</th>
      <th>State</th>
      <th>Identifier</th>
      <th>Issuer</th>
    </thead>
    <tbody>
      <% @provider.provider_identifiers.each do |ident| %>
        <tr>
          <td><%= ident.type %></td>
          <td><%= ident.state %></td>
          <td><%= ident.identifier %></td>
          <td><%= ident.additional_info %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</fieldset>

<%= link_to 'Back', providers_path %>